# Generated by Django 4.2.7 on 2025-12-04 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
